# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Bookmark Title')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Bookmark Description')),
                ('xmin', models.FloatField(blank=True, null=True, verbose_name='xmin')),
                ('ymin', models.FloatField(blank=True, null=True, verbose_name='ymin')),
                ('xmax', models.FloatField(blank=True, null=True, verbose_name='xmax')),
                ('ymax', models.FloatField(blank=True, null=True, verbose_name='ymax')),
                ('zoom_level', models.IntegerField(blank=True, null=True, verbose_name='Zoom Level')),
            ],
        ),
    ]
